name: i2k-2020
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.7
  - conda-forge::numpy=1.18.*
  - conda-forge::matplotlib
  - conda-forge::jupyter
  - conda-forge::pyopencl
  - conda-forge::pip
  - pip:
    - tensorflow==2.3.*
    - csbdeep
    - stardist
    - gputools